language: java

jdk:
#  - openjdk8
  - oraclejdk8

env:
  - MAVEN=3.6.0

cache:
  directories:
    - ${HOME}/.m2


before_install:
  - ulimit -a && free -m
  - chmod +x .travis/*
  - echo ${GPG_PUBLIC_KEYS}  | base64 --decode > /tmp/frekele-pubkey.asc
  - echo ${GPG_PRIVATE_KEYS} | base64 --decode > /tmp/frekele-privkey.asc
  - echo ${GPG_OWNERTRUST}   | base64 --decode > /tmp/frekele-ownertrust.asc
  #- gpg --keyserver pgp.mit.edu --recv-key ${FREKELE_GPGKEY}
  - gpg --import /tmp/frekele-pubkey.asc
  - gpg --import /tmp/frekele-privkey.asc
  - gpg --import-ownertrust /tmp/frekele-ownertrust.asc
  - sudo rm -f /etc/mavenrc && sudo rm -f ${HOME}/.mavenrc
  - export MVN_HOME=/tmp/maven-${MAVEN} && export M2_HOME=${MVN_HOME}
  - mkdir ${MVN_HOME}
  - export MAVEN_OPTS="-Dmaven.repo.local=${HOME}/.m2/repository -Xms1024m -Xmx4096m -XX:PermSize=512m"
  - export PATH=${MVN_HOME}/bin:$PATH
  - sudo apt-get install -qq jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar "https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar"
  #- wget -O ~/codacy-coverage-reporter-assembly-latest.jar "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.codacy&a=codacy-coverage-reporter&v=LATEST"
  #- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

install:
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C ${MVN_HOME}

before_script:

script:
  - ${MVN_HOME}/bin/mvn --settings .travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -V
  - ulimit -a && free -m

before_cache:

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml

after_failure:
  - echo "FAILURE"
  - ulimit -a
  - free -m

before_deploy:

deploy:
  -
    provider: script
    script:
      - .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script:
      - .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      tags: true
      jdk: oraclejdk8

after_deploy:

after_script:
