language: java

jdk:
#  - openjdk8
  - oraclejdk8

env:
  - MAVEN=3.5.0

cache:
  directories:
    - $HOME/.m2

before_install:
  - cat $HOME/.m2/settings.xml
  - gpg --keyserver pgp.mit.edu --recv-key ${FREKELE_GPGKEY}
  #- gpg --keyserver keys.gnupg.net --recv-key ${FREKELE_GPGKEY}
  - gpg --list-keys
  - export M2_HOME=/tmp/maven-${MAVEN}
  - mkdir $M2_HOME
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C $M2_HOME
  - export PATH=$M2_HOME/bin:$PATH

install:
  - $M2_HOME/bin/mvn --settings .travis/settings.xml install -Dgpg.skip -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -V

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      tags: true
      jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
