dist: xenial
language: java

jdk:
#  - openjdk8
  - oraclejdk8

env:
  - MAVEN=3.5.0
  - CORE_UTILS=8.27

cache:
  directories:
    - ${HOME}/.m2
    #- ${HOME}/coreutils


before_install:
  - wget -qO- https://ftp.gnu.org/gnu/coreutils/coreutils-${CORE_UTILS}.tar.xz -O /tmp/coreutils-${CORE_UTILS}.tar.xz
  - tar -xf /tmp/coreutils-${CORE_UTILS}.tar.xz -C /tmp/
  - export FORCE_UNSAFE_CONFIGURE=1
  - /tmp/coreutils-${CORE_UTILS}/configure --prefix=${HOME}/coreutils --libexecdir=${HOME}/coreutils/lib --enable-no-install-program=kill,uptime && make && make install
  - ${HOME}/coreutils/bin/base64 --version
  
  #- echo ${GPG_PUBLIC_KEYS} | base64 -di > /tmp/frekele-pubkey.asc
  - echo ${GPG_SECRET_KEYS} | base64 -di > /tmp/frekele-privkey.asc
  - cat /tmp/frekele-privkey.asc
  - echo ${GPG_OWNERTRUST} | base64 -di > /tmp/frekele-ownertrust.asc
  - cat /tmp/frekele-ownertrust.asc
  - gpg --keyserver pgp.mit.edu --recv-key ${FREKELE_GPGKEY}
  #- gpg --import /tmp/frekele-pubkey.asc
  - gpg --import /tmp/frekele-privkey.asc
  - gpg --import-ownertrust /tmp/frekele-ownertrust.asc
  - gpg --list-sigs
  - gpg --list-secret-keys
  - export MVN_HOME=/tmp/maven-${MAVEN}
  - mkdir ${MVN_HOME}
  - export PATH=${MVN_HOME}/bin:$PATH


install:
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C ${MVN_HOME}


before_script:


script:
  - ${MVN_HOME}/bin/mvn --settings .travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -V


before_cache:


after_success:
  - bash <(curl -s https://codecov.io/bash)


after_failure:


before_deploy:


deploy:
  -
    provider: script
    script:
      - ${MVN_HOME}/bin/mvn clean deploy --settings .travis/settings.xml -DskipTests=true -B -U
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script:
      - ${MVN_HOME}/bin/mvn --settings .travis/settings.xml org.codehaus.mojo:versions-maven-plugin:2.4:set -DnewVersion=${TRAVIS_TAG}
      - ${MVN_HOME}/bin/mvn clean deploy --settings .travis/settings.xml -B -U
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      tags: true
      jdk: oraclejdk8


after_deploy:


after_script:
