language: java

jdk:
#  - openjdk8
  - oraclejdk8

install:
  - mvn --settings .travis/settings.xml install -Dgpg.skip -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -V

before_install:
  - gpg --list-keys
  - gpg --keyserver pgp.mit.edu --recv-key ${FREKELE_GPGKEY} | gpg --keyserver keys.gnupg.net --recv-key ${FREKELE_GPGKEY}
  - gpg --list-keys

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: frekele/elasticsearch-mapping-builder
      tags: true
      jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
